// Package generator generates migrations for the Oasis Indexer
// from the genesis file at a particular height.
package generator

import (
	"fmt"
	"os"
	"strings"

	"github.com/oasisprotocol/oasis-core/go/common/entity"
	"github.com/oasisprotocol/oasis-core/go/common/node"
	genesis "github.com/oasisprotocol/oasis-core/go/genesis/api"

	"github.com/oasislabs/oasis-block-indexer/go/log"
)

const (
	mainnetContext = "b11b369e0da5bb230b220127f5e7b242d385ef8c6f54906243f30af63c815535"
)

// MigrationGenerator generates migrations for the Oasis Indexer
// target storage.
type MigrationGenerator struct {
	logger *log.Logger
}

// NewMigrationGenerator creates a new migration generator.
func NewMigrationGenerator(logger *log.Logger) *MigrationGenerator {
	return &MigrationGenerator{logger}
}

// WriteGenesisDocumentMigration writes the SQL migration for the genesis document
// into a file.
func (mg *MigrationGenerator) WriteGenesisDocumentMigration(filename string, document *genesis.Document) error {
	migration, err := mg.GenesisDocumentMigration(document)
	if err != nil {
		return err
	}

	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	_, err = f.WriteString(migration)
	if err != nil {
		return err
	}

	return nil
}

// GenesisDocumentMigration creates a new migration that re-initializes all
// height-dependent state as per the provided genesis document.
func (mg *MigrationGenerator) GenesisDocumentMigration(document *genesis.Document) (string, error) {
	fmt.Println("genesis document")
	fmt.Println(document.ChainID)
	fmt.Println(document.Height)
	var b strings.Builder
	b.WriteString(`-- DO NOT MODIFY
-- This file was autogenerated by the oasis-indexer migration generator.

BEGIN;
`)

	for _, f := range []func(*strings.Builder, *genesis.Document) error{
		mg.addRegistryBackendMigrations,
		mg.addStakingBackendMigrations,
		mg.addGovernanceBackendMigrations,
	} {
		if err := f(&b, document); err != nil {
			return "", err
		}
	}

	b.WriteString("\n\nCOMMIT;\n")

	return b.String(), nil
}

func (mg *MigrationGenerator) addRegistryBackendMigrations(b *strings.Builder, document *genesis.Document) error {

	registry := document.Registry

	// Populate entities.
	b.WriteString(fmt.Sprintf(`
-- Registry Backend Data
TRUNCATE %s.entities CASCADE;`, document.ChainID))
	b.WriteString(fmt.Sprintf(`
INSERT INTO %s.entities (id)
VALUES
`, document.ChainID))
	for i, signedEntity := range registry.Entities {
		var entity entity.Entity
		if err := signedEntity.Open(mainnetContext, &entity); err != nil {
			return err
		}

		b.WriteString(fmt.Sprintf(
			"\t('%s')",
			entity.ID.String(),
		))

		if i != len(registry.Entities)-1 {
			b.WriteString(",\n")
		}
	}
	b.WriteString(";\n")

	// Populate nodes.
	b.WriteString(fmt.Sprintf(`
TRUNCATE %s.nodes CASCADE;`, document.ChainID))
	b.WriteString(fmt.Sprintf(`
INSERT INTO %s.nodes (id, entity_id, expiration, tls_pubkey, tls_next_pubkey, p2p_pubkey, consensus_pubkey, roles)
VALUES
`, document.ChainID))
	for i, signedNode := range registry.Nodes {
		var node node.Node
		if err := signedNode.Open(mainnetContext, &node); err != nil {
			return err
		}

		b.WriteString(fmt.Sprintf(
			"\t('%s', '%s', %d, '%s', '%s', '%s', '%s', '%s')",
			node.ID.String(),
			node.EntityID.String(),
			node.Expiration,
			node.TLS.PubKey.String(),
			node.TLS.NextPubKey.String(),
			node.P2P.ID.String(),
			node.Consensus.ID.String(),
			node.Roles.String(),
		))

		if i != len(registry.Nodes)-1 {
			b.WriteString(",\n")
		}
	}
	b.WriteString(";\n")

	// Populate runtimes.
	b.WriteString(fmt.Sprintf(`
TRUNCATE %s.runtimes CASCADE;`, document.ChainID))
	b.WriteString(fmt.Sprintf(`
INSERT INTO %s.runtimes (id, suspended, kind, tee_hardware, key_manager)
VALUES
`, document.ChainID))
	for i, runtime := range registry.Runtimes {
		keyManager := "none"
		if runtime.KeyManager != nil {
			keyManager = runtime.KeyManager.String()
		}
		b.WriteString(fmt.Sprintf(
			"\t('%s', %t, '%s', '%s', '%s')",
			runtime.ID.String(),
			false,
			runtime.Kind.String(),
			runtime.TEEHardware.String(),
			keyManager,

			// TODO(ennsharma): Add extra_data.
		))

		if i != len(registry.Runtimes)-1 {
			b.WriteString(",\n")
		}
	}
	b.WriteString(";\n")

	b.WriteString(fmt.Sprintf(`
INSERT INTO %s.runtimes (id, suspended, kind, tee_hardware, key_manager, extra_data)
VALUES
`, document.ChainID))

	for i, runtime := range registry.SuspendedRuntimes {
		keyManager := "none"
		if runtime.KeyManager != nil {
			keyManager = runtime.KeyManager.Hex()
		}
		b.WriteString(fmt.Sprintf(
			"\t('%s', %t, '%s', '%s', '%s')",
			runtime.ID.String(),
			true,
			runtime.Kind.String(),
			runtime.TEEHardware.String(),
			keyManager,

			// TODO(ennsharma): Add extra_data.
		))

		if i != len(registry.SuspendedRuntimes)-1 {
			b.WriteString(",\n")
		}
	}
	b.WriteString(";\n")

	return nil
}

func (mg *MigrationGenerator) addStakingBackendMigrations(b *strings.Builder, document *genesis.Document) error {

	staking := document.Staking

	// Populate accounts.
	b.WriteString(fmt.Sprintf(`
-- Staking Backend Data
TRUNCATE %s.accounts CASCADE;`, document.ChainID))
	b.WriteString(fmt.Sprintf(`
INSERT INTO %s.accounts (address, general_balance, nonce, escrow_balance_active, escrow_total_shares_active, escrow_balance_debonding, escrow_total_shares_debonding)
VALUES
`, document.ChainID))

	i := 0
	for address, account := range staking.Ledger {
		b.WriteString(fmt.Sprintf(
			"\t('%s', %d, %d, %d, %d, %d, %d)",
			address.String(),
			account.General.Balance.ToBigInt(),
			account.General.Nonce,
			account.Escrow.Active.Balance.ToBigInt(),
			account.Escrow.Active.TotalShares.ToBigInt(),
			account.Escrow.Debonding.Balance.ToBigInt(),
			account.Escrow.Debonding.TotalShares.ToBigInt(),
		))
		i++

		if i != len(staking.Ledger) {
			b.WriteString(",\n")
		}
	}
	b.WriteString(";\n")

	// Populate allowances.
	b.WriteString(fmt.Sprintf(`
TRUNCATE %s.allowances CASCADE;`, document.ChainID))

	foundAllowances := false // in case allowances are empty

	i = 0
	for owner, account := range staking.Ledger {
		if len(account.General.Allowances) > 0 && !foundAllowances {
			b.WriteString(fmt.Sprintf(`
INSERT INTO %s.allowances (owner, beneficiary, allowance)
VALUES
`, document.ChainID))
			foundAllowances = true
		}

		ownerAllowances := make([]string, len(account.General.Allowances))
		j := 0
		for beneficiary, allowance := range account.General.Allowances {
			ownerAllowances[j] = fmt.Sprintf(
				"\t('%s', '%s', %d)",
				owner.String(),
				beneficiary.String(),
				allowance.ToBigInt(),
			)
			j++
		}
		b.WriteString(strings.Join(ownerAllowances, ",\n"))
		i++

		if i != len(staking.Ledger) && len(account.General.Allowances) > 0 {
			b.WriteString(",\n")
		}
	}
	if foundAllowances {
		b.WriteString(";\n")
	}

	// Populate delegations.
	b.WriteString(fmt.Sprintf(`
TRUNCATE %s.delegations CASCADE;`, document.ChainID))
	b.WriteString(fmt.Sprintf(`
INSERT INTO %s.delegations (delegatee, delegator, shares)
VALUES
`, document.ChainID))
	i = 0
	for delegatee, escrows := range staking.Delegations {
		delegateeDelegations := make([]string, len(escrows))
		j := 0
		for delegator, delegation := range escrows {
			delegateeDelegations[j] = fmt.Sprintf(
				"\t('%s', '%s', %d)",
				delegatee.String(),
				delegator.String(),
				delegation.Shares.ToBigInt(),
			)
			j++
		}
		b.WriteString(strings.Join(delegateeDelegations, ",\n"))
		i++

		if i != len(staking.Delegations) && len(escrows) > 0 {
			b.WriteString(",\n")
		}
	}
	b.WriteString(";\n")

	// Populate debonding delegations.
	b.WriteString(fmt.Sprintf(`
TRUNCATE %s.debonding_delegations CASCADE;`, document.ChainID))
	b.WriteString(fmt.Sprintf(`
INSERT INTO %s.debonding_delegations (delegatee, delegator, shares, debond_end)
VALUES
`, document.ChainID))
	i = 0
	for delegatee, escrows := range staking.DebondingDelegations {
		delegateeDebondingDelegations := make([]string, 0)
		j := 0
		for delegator, debondingDelegations := range escrows {
			delegatorDebondingDelegations := make([]string, len(debondingDelegations))
			for k, debondingDelegation := range debondingDelegations {
				delegatorDebondingDelegations[k] = fmt.Sprintf(
					"\t('%s', '%s', %d, %d)",
					delegatee.String(),
					delegator.String(),
					debondingDelegation.Shares.ToBigInt(),
					debondingDelegation.DebondEndTime,
				)
			}
			delegateeDebondingDelegations = append(delegateeDebondingDelegations, delegatorDebondingDelegations...)
			j++
		}
		b.WriteString(strings.Join(delegateeDebondingDelegations, ",\n"))
		i++

		if i != len(staking.DebondingDelegations) && len(escrows) > 0 {
			b.WriteString(",\n")
		}
	}
	b.WriteString(";\n")

	return nil
}

func (mg *MigrationGenerator) addGovernanceBackendMigrations(b *strings.Builder, document *genesis.Document) error {

	governance := document.Governance

	// Populate proposals.
	b.WriteString(fmt.Sprintf(`
-- Governance Backend Data
TRUNCATE %s.proposals CASCADE;`, document.ChainID))

	if len(governance.Proposals) > 0 {

		// TODO(ennsharma): Extract `executed` for proposal.
		b.WriteString(fmt.Sprintf(`
INSERT INTO %s.proposals (id, submitter, state, deposit, handler, cp_target_version, rhp_target_version, rcp_target_version, upgrade_epoch, cancels, created_at, closes_at, invalid_votes)
VALUES
`, document.ChainID))

		for i, proposal := range governance.Proposals {
			if proposal.Content.Upgrade != nil {
				b.WriteString(fmt.Sprintf(
					"\t(%d, '%s', '%s', %d, '%s', '%s', '%s', '%s', %d, %d, %d, %d, %d)",
					proposal.ID,
					proposal.Submitter.String(),
					proposal.State.String(),
					proposal.Deposit.ToBigInt(),
					proposal.Content.Upgrade.Handler,
					proposal.Content.Upgrade.Target.ConsensusProtocol.String(),
					proposal.Content.Upgrade.Target.RuntimeHostProtocol.String(),
					proposal.Content.Upgrade.Target.RuntimeCommitteeProtocol.String(),
					proposal.Content.Upgrade.Epoch,
					0,
					proposal.CreatedAt,
					proposal.ClosesAt,
					proposal.InvalidVotes,
				))
			} else if proposal.Content.CancelUpgrade != nil {
				b.WriteString(fmt.Sprintf(
					"\t(%d, '%s', '%s', %d, '%s', '%s', '%s', '%s', '%s', %d, %d, %d, %d)",
					proposal.ID,
					proposal.Submitter.String(),
					proposal.State.String(),
					proposal.Deposit.ToBigInt(),
					"",
					"",
					"",
					"",
					"",
					proposal.Content.CancelUpgrade.ProposalID,
					proposal.CreatedAt,
					proposal.ClosesAt,
					proposal.InvalidVotes,
				))
			}

			if i != len(governance.Proposals) {
				b.WriteString(",\n")
			}
		}
		b.WriteString(";\n")
	}

	// Populate votes.
	b.WriteString(fmt.Sprintf(`
TRUNCATE %s.votes CASCADE;`, document.ChainID))

	foundVotes := false // in case votes are empty

	i := 0
	for proposalID, voteEntries := range governance.VoteEntries {
		if len(voteEntries) > 0 && !foundVotes {
			b.WriteString(fmt.Sprintf(`
INSERT INTO %s.votes (proposal, voter, vote)
VALUES
`, document.ChainID))
			foundVotes = true
		}
		votes := make([]string, len(voteEntries))
		for j, voteEntry := range voteEntries {
			votes[j] = fmt.Sprintf(
				"\t(%d, '%s', '%s')",
				proposalID,
				voteEntry.Voter.String(),
				voteEntry.Vote.String(),
			)
		}
		b.WriteString(strings.Join(votes, ",\n"))
		i++

		if i != len(governance.VoteEntries) && len(voteEntries) > 0 {
			b.WriteString(",\n")
		}
	}
	if foundVotes {
		b.WriteString(";\n")
	}

	return nil
}
