# golangci-lint configuration.

# For more information, see:
# https://golangci-lint.run/usage/configuration/.

run:
  timeout: 5m
  skip-dirs:
    - storage/generator

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - govet

linters:
  # Disable all linters except the ones explicitly listed below.
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - sqlclosecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  exhaustive:
    # Switch statements are to be considered exhaustive if a 'default' case is
    # present, even if all enum members aren't listed in the switch.
    default-signifies-exhaustive: true
  govet:
    # Enabled checking for shadowed variables.
    check-shadowing: true
  goimports:
    # Put local imports after 3rd-party packages.
    local-prefixes: github.com/oasislabs/oasis-indexer
