project_name: Oasis Nexus

before:
  hooks:
    - go mod tidy -compat=1.21

builds:
  - binary: nexus
    env:
      - CGO_ENABLED=0  # build statically-linked binaries
    flags:
      - -trimpath
    ldflags:
      - -buildid=
      - "{{.Env.GOLDFLAGS_VERSION}}"
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{replace .ProjectName \" \" \"_\" | tolower}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    wrap_in_directory: "true"

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  name_template: "{{.ProjectName}} {{.Version}}"

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1.
  prerelease: auto

  footer: |
    **Full Changelog**: https://github.com/oasisprotocol/nexus/compare/{{ .PreviousTag }}...{{ .Tag }}
    ### Running Nexus in Docker
    https://github.com/oasisprotocol/nexus/blob/{{ .Tag }}/README.md#docker-development
