# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json

# markdownlint configuration.

# For more information, see:
# https://github.com/DavidAnson/markdownlint#optionsconfig.

# Enable all rules.
default: true

line-length: # https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md013.md
  # "strict" disallows long lines even if they have spaces. It's not the default.
  strict: false  
  line_length: 80
  # Allow longer lines for code blocks.
  code_block_line_length: 100

# Do not always require language specifiers with fenced code blocks since they
# are not part of the Markdown spec.
fenced-code-language: false
