// Package v1 implements the Nexus API v1.
package v1

import (
	"context"
	"encoding/hex"
	"fmt"

	apiTypes "github.com/oasisprotocol/nexus/api/v1/types"
	"github.com/oasisprotocol/nexus/common"
	"github.com/oasisprotocol/nexus/log"
	"github.com/oasisprotocol/nexus/storage/client"
)

// StrictServerImpl implements the oapi-codegen StrictServerInterface interface,
// which exposes our API endpoints as functions with strongly-typed params.
// This struct is a thin layer over the DB-querying client; it mostly just forwards
// the inputs and outputs, but sometimes it additionally processes them.
type StrictServerImpl struct {
	dbClient client.StorageClient
	logger   log.Logger
}

var _ apiTypes.StrictServerInterface = (*StrictServerImpl)(nil)

func NewStrictServerImpl(client client.StorageClient, logger log.Logger) *StrictServerImpl {
	return &StrictServerImpl{
		dbClient: client,
		logger:   logger,
	}
}

// Stubs of these functions were derived from the autogenerated interface with:
//	sed -n '/type StrictServerInterface interface/,/^\}/p' api/v1/types/server.gen.go | grep -v // | head -n-1 | tail -n+2 | sed -E 's/^\s+(\w+)(.*)/func (srv *StrictServerImpl) \1\2 { return apiTypes.\1200JSONResponse{}, nil }\n/g; s/[a-zA-Z]+(Params|RequestObject|ResponseObject)/apiTypes.\0/g;'

func (srv *StrictServerImpl) GetStatus(ctx context.Context, request apiTypes.GetStatusRequestObject) (apiTypes.GetStatusResponseObject, error) {
	status, err := srv.dbClient.Status(ctx)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetStatus200JSONResponse(*status), nil
}

func (srv *StrictServerImpl) GetConsensusTotalSupplyRaw(ctx context.Context, request apiTypes.GetConsensusTotalSupplyRawRequestObject) (apiTypes.GetConsensusTotalSupplyRawResponseObject, error) {
	totalSupply, err := srv.dbClient.TotalSupply(ctx)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusTotalSupplyRaw200TextResponse(totalSupply.String()), nil
}

func (srv *StrictServerImpl) GetConsensusCirculatingSupplyRaw(ctx context.Context, request apiTypes.GetConsensusCirculatingSupplyRawRequestObject) (apiTypes.GetConsensusCirculatingSupplyRawResponseObject, error) {
	circulatingSupply, err := srv.dbClient.CirculatingSupply(ctx)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusCirculatingSupplyRaw200TextResponse(circulatingSupply.String()), nil
}

func (srv *StrictServerImpl) GetConsensusAccounts(ctx context.Context, request apiTypes.GetConsensusAccountsRequestObject) (apiTypes.GetConsensusAccountsResponseObject, error) {
	accounts, err := srv.dbClient.Accounts(ctx, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusAccounts200JSONResponse(*accounts), nil
}

func (srv *StrictServerImpl) GetConsensusAccountsAddress(ctx context.Context, request apiTypes.GetConsensusAccountsAddressRequestObject) (apiTypes.GetConsensusAccountsAddressResponseObject, error) {
	account, err := srv.dbClient.Account(ctx, request.Address)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusAccountsAddress200JSONResponse(*account), nil
}

func (srv *StrictServerImpl) GetConsensusAccountsAddressDebondingDelegations(ctx context.Context, request apiTypes.GetConsensusAccountsAddressDebondingDelegationsRequestObject) (apiTypes.GetConsensusAccountsAddressDebondingDelegationsResponseObject, error) {
	delegations, err := srv.dbClient.DebondingDelegations(ctx, request.Address, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusAccountsAddressDebondingDelegations200JSONResponse(*delegations), nil
}

func (srv *StrictServerImpl) GetConsensusAccountsAddressDebondingDelegationsTo(ctx context.Context, request apiTypes.GetConsensusAccountsAddressDebondingDelegationsToRequestObject) (apiTypes.GetConsensusAccountsAddressDebondingDelegationsToResponseObject, error) {
	delegations, err := srv.dbClient.DebondingDelegationsTo(ctx, request.Address, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusAccountsAddressDebondingDelegationsTo200JSONResponse(*delegations), nil
}

func (srv *StrictServerImpl) GetConsensusAccountsAddressDelegations(ctx context.Context, request apiTypes.GetConsensusAccountsAddressDelegationsRequestObject) (apiTypes.GetConsensusAccountsAddressDelegationsResponseObject, error) {
	delegations, err := srv.dbClient.Delegations(ctx, request.Address, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusAccountsAddressDelegations200JSONResponse(*delegations), nil
}

func (srv *StrictServerImpl) GetConsensusAccountsAddressDelegationsTo(ctx context.Context, request apiTypes.GetConsensusAccountsAddressDelegationsToRequestObject) (apiTypes.GetConsensusAccountsAddressDelegationsToResponseObject, error) {
	delegations, err := srv.dbClient.DelegationsTo(ctx, request.Address, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusAccountsAddressDelegationsTo200JSONResponse(*delegations), nil
}

func (srv *StrictServerImpl) GetConsensusBlocks(ctx context.Context, request apiTypes.GetConsensusBlocksRequestObject) (apiTypes.GetConsensusBlocksResponseObject, error) {
	blocks, err := srv.dbClient.Blocks(ctx, request.Params, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusBlocks200JSONResponse(*blocks), nil
}

func (srv *StrictServerImpl) GetConsensusBlocksHeight(ctx context.Context, request apiTypes.GetConsensusBlocksHeightRequestObject) (apiTypes.GetConsensusBlocksHeightResponseObject, error) {
	blocks, err := srv.dbClient.Blocks(ctx, apiTypes.GetConsensusBlocksParams{}, &request.Height)
	if err != nil {
		return nil, err
	}
	if len(blocks.Blocks) == 0 {
		return apiTypes.GetConsensusBlocksHeight404JSONResponse{}, nil
	}
	return apiTypes.GetConsensusBlocksHeight200JSONResponse(blocks.Blocks[0]), nil
}

func (srv *StrictServerImpl) GetConsensusRoothashMessages(ctx context.Context, request apiTypes.GetConsensusRoothashMessagesRequestObject) (apiTypes.GetConsensusRoothashMessagesResponseObject, error) {
	roothashMessages, err := srv.dbClient.RoothashMessages(ctx, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusRoothashMessages200JSONResponse(*roothashMessages), nil
}

func (srv *StrictServerImpl) GetConsensusEntities(ctx context.Context, request apiTypes.GetConsensusEntitiesRequestObject) (apiTypes.GetConsensusEntitiesResponseObject, error) {
	entities, err := srv.dbClient.Entities(ctx, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusEntities200JSONResponse(*entities), nil
}

func (srv *StrictServerImpl) GetConsensusEntitiesAddress(ctx context.Context, request apiTypes.GetConsensusEntitiesAddressRequestObject) (apiTypes.GetConsensusEntitiesAddressResponseObject, error) {
	entity, err := srv.dbClient.Entity(ctx, request.Address)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusEntitiesAddress200JSONResponse(*entity), nil
}

func (srv *StrictServerImpl) GetConsensusEntitiesAddressNodes(ctx context.Context, request apiTypes.GetConsensusEntitiesAddressNodesRequestObject) (apiTypes.GetConsensusEntitiesAddressNodesResponseObject, error) {
	nodes, err := srv.dbClient.EntityNodes(ctx, request.Address, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusEntitiesAddressNodes200JSONResponse(*nodes), nil
}

func (srv *StrictServerImpl) GetConsensusEntitiesAddressNodesNodeId(ctx context.Context, request apiTypes.GetConsensusEntitiesAddressNodesNodeIdRequestObject) (apiTypes.GetConsensusEntitiesAddressNodesNodeIdResponseObject, error) {
	node, err := srv.dbClient.EntityNode(ctx, request.Address, request.NodeId)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusEntitiesAddressNodesNodeId200JSONResponse(*node), nil
}

func (srv *StrictServerImpl) GetConsensusEpochs(ctx context.Context, request apiTypes.GetConsensusEpochsRequestObject) (apiTypes.GetConsensusEpochsResponseObject, error) {
	epochs, err := srv.dbClient.Epochs(ctx, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusEpochs200JSONResponse(*epochs), nil
}

func (srv *StrictServerImpl) GetConsensusEpochsEpoch(ctx context.Context, request apiTypes.GetConsensusEpochsEpochRequestObject) (apiTypes.GetConsensusEpochsEpochResponseObject, error) {
	epoch, err := srv.dbClient.Epoch(ctx, request.Epoch)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusEpochsEpoch200JSONResponse(*epoch), nil
}

func (srv *StrictServerImpl) GetConsensusEvents(ctx context.Context, request apiTypes.GetConsensusEventsRequestObject) (apiTypes.GetConsensusEventsResponseObject, error) {
	// Additional param validation.
	if request.Params.Type != nil && !request.Params.Type.IsValid() {
		return nil, &apiTypes.InvalidParamFormatError{ParamName: "type", Err: fmt.Errorf("not a valid enum value: %s", *request.Params.Type)}
	}
	if request.Params.TxIndex != nil && request.Params.Block == nil {
		return nil, &apiTypes.InvalidParamFormatError{ParamName: "block", Err: fmt.Errorf("must be specified when tx_index is specified")}
	}

	events, err := srv.dbClient.Events(ctx, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusEvents200JSONResponse(*events), nil
}

func (srv *StrictServerImpl) GetConsensusProposals(ctx context.Context, request apiTypes.GetConsensusProposalsRequestObject) (apiTypes.GetConsensusProposalsResponseObject, error) {
	proposals, err := srv.dbClient.Proposals(ctx, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusProposals200JSONResponse(*proposals), nil
}

func (srv *StrictServerImpl) GetConsensusProposalsProposalId(ctx context.Context, request apiTypes.GetConsensusProposalsProposalIdRequestObject) (apiTypes.GetConsensusProposalsProposalIdResponseObject, error) {
	proposal, err := srv.dbClient.Proposal(ctx, request.ProposalId)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusProposalsProposalId200JSONResponse(*proposal), nil
}

func (srv *StrictServerImpl) GetConsensusProposalsProposalIdVotes(ctx context.Context, request apiTypes.GetConsensusProposalsProposalIdVotesRequestObject) (apiTypes.GetConsensusProposalsProposalIdVotesResponseObject, error) {
	votes, err := srv.dbClient.ProposalVotes(ctx, request.ProposalId, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusProposalsProposalIdVotes200JSONResponse(*votes), nil
}

func (srv *StrictServerImpl) GetLayerStatsTxVolume(ctx context.Context, request apiTypes.GetLayerStatsTxVolumeRequestObject) (apiTypes.GetLayerStatsTxVolumeResponseObject, error) {
	// Additional param validation.
	if !request.Layer.IsValid() {
		return nil, &apiTypes.InvalidParamFormatError{ParamName: "layer", Err: fmt.Errorf("not a valid enum value: %s", request.Layer)}
	}

	volumeList, err := srv.dbClient.TxVolumes(ctx, request.Layer, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetLayerStatsTxVolume200JSONResponse(*volumeList), nil
}

func (srv *StrictServerImpl) GetLayerStatsActiveAccounts(ctx context.Context, request apiTypes.GetLayerStatsActiveAccountsRequestObject) (apiTypes.GetLayerStatsActiveAccountsResponseObject, error) {
	// Additional param validation.
	if !request.Layer.IsValid() {
		return nil, &apiTypes.InvalidParamFormatError{ParamName: "layer", Err: fmt.Errorf("not a valid enum value: %s", request.Layer)}
	}
	if err := request.Params.Validate(); err != nil {
		return nil, err
	}

	activeAccountsList, err := srv.dbClient.DailyActiveAccounts(ctx, request.Layer, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetLayerStatsActiveAccounts200JSONResponse(*activeAccountsList), nil
}

func (srv *StrictServerImpl) GetConsensusTransactions(ctx context.Context, request apiTypes.GetConsensusTransactionsRequestObject) (apiTypes.GetConsensusTransactionsResponseObject, error) {
	txs, err := srv.dbClient.Transactions(ctx, request.Params, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusTransactions200JSONResponse(*txs), nil
}

func (srv *StrictServerImpl) GetConsensusTransactionsTxHash(ctx context.Context, request apiTypes.GetConsensusTransactionsTxHashRequestObject) (apiTypes.GetConsensusTransactionsTxHashResponseObject, error) {
	txs, err := srv.dbClient.Transactions(ctx, apiTypes.GetConsensusTransactionsParams{}, &request.TxHash)
	if err != nil {
		return nil, err
	}
	if len(txs.Transactions) == 0 {
		return apiTypes.GetConsensusTransactionsTxHash404JSONResponse{}, nil
	}
	return apiTypes.GetConsensusTransactionsTxHash200JSONResponse(*txs), nil
}

func (srv *StrictServerImpl) GetConsensusValidators(ctx context.Context, request apiTypes.GetConsensusValidatorsRequestObject) (apiTypes.GetConsensusValidatorsResponseObject, error) {
	validators, err := srv.dbClient.Validators(ctx, request.Params, nil /*entityID*/)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusValidators200JSONResponse(*validators), nil
}

func (srv *StrictServerImpl) GetConsensusValidatorsAddress(ctx context.Context, request apiTypes.GetConsensusValidatorsAddressRequestObject) (apiTypes.GetConsensusValidatorsAddressResponseObject, error) {
	validators, err := srv.dbClient.Validators(ctx, apiTypes.GetConsensusValidatorsParams{Limit: common.Ptr(uint64(1))}, &request.Address)
	if err != nil {
		return nil, err
	}
	if len(validators.Validators) == 0 {
		return apiTypes.GetConsensusValidatorsAddress404JSONResponse{}, nil
	}
	// Truncate ValidatorList to only include the top matching validator.
	if len(validators.Validators) > 1 {
		validators.Validators = validators.Validators[:1]
	}
	return apiTypes.GetConsensusValidatorsAddress200JSONResponse(*validators), nil
}

func (srv *StrictServerImpl) GetConsensusValidatorsAddressHistory(ctx context.Context, request apiTypes.GetConsensusValidatorsAddressHistoryRequestObject) (apiTypes.GetConsensusValidatorsAddressHistoryResponseObject, error) {
	history, err := srv.dbClient.ValidatorHistory(ctx, request.Address, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetConsensusValidatorsAddressHistory200JSONResponse(*history), nil
}

func (srv *StrictServerImpl) GetRuntimeBlocks(ctx context.Context, request apiTypes.GetRuntimeBlocksRequestObject) (apiTypes.GetRuntimeBlocksResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	blocks, err := srv.dbClient.RuntimeBlocks(ctx, runtime, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeBlocks200JSONResponse(*blocks), nil
}

func (srv *StrictServerImpl) GetRuntimeEvmTokens(ctx context.Context, request apiTypes.GetRuntimeEvmTokensRequestObject) (apiTypes.GetRuntimeEvmTokensResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	tokens, err := srv.dbClient.RuntimeTokens(ctx, runtime, request.Params, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeEvmTokens200JSONResponse(*tokens), nil
}

func (srv *StrictServerImpl) GetRuntimeEvmTokensAddress(ctx context.Context, request apiTypes.GetRuntimeEvmTokensAddressRequestObject) (apiTypes.GetRuntimeEvmTokensAddressResponseObject, error) {
	ocAddr, err := apiTypes.UnmarshalToOcAddress(&request.Address)
	if err != nil {
		return nil, err
	}
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	tokens, err := srv.dbClient.RuntimeTokens(ctx, runtime, apiTypes.GetRuntimeEvmTokensParams{Limit: common.Ptr(uint64(1))}, ocAddr)
	if err != nil {
		return nil, err
	}
	if len(tokens.EvmTokens) != 1 {
		return apiTypes.GetRuntimeEvmTokensAddress404JSONResponse{}, nil
	}
	return apiTypes.GetRuntimeEvmTokensAddress200JSONResponse(tokens.EvmTokens[0]), nil
}

func (srv *StrictServerImpl) GetRuntimeEvmTokensAddressHolders(ctx context.Context, request apiTypes.GetRuntimeEvmTokensAddressHoldersRequestObject) (apiTypes.GetRuntimeEvmTokensAddressHoldersResponseObject, error) {
	ocAddr, err := apiTypes.UnmarshalToOcAddress(&request.Address)
	if err != nil {
		return nil, err
	}
	// request.Address is a required field and so ocAddr should never be nil
	// Nevertheless, we check again for clarity.
	if ocAddr == nil {
		return nil, fmt.Errorf("missing required param: address")
	}
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	holders, err := srv.dbClient.RuntimeTokenHolders(ctx, runtime, request.Params, *ocAddr)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeEvmTokensAddressHolders200JSONResponse(*holders), nil
}

func (srv *StrictServerImpl) GetRuntimeEvmTokensAddressNfts(ctx context.Context, request apiTypes.GetRuntimeEvmTokensAddressNftsRequestObject) (apiTypes.GetRuntimeEvmTokensAddressNftsResponseObject, error) {
	ocAddr, err := apiTypes.UnmarshalToOcAddress(&request.Address)
	if err != nil {
		return nil, err
	}
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	nfts, err := srv.dbClient.RuntimeEVMNFTs(ctx, runtime, request.Params.Limit, request.Params.Offset, ocAddr, nil, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeEvmTokensAddressNfts200JSONResponse(*nfts), nil
}

func (srv *StrictServerImpl) GetRuntimeEvmTokensAddressNftsId(ctx context.Context, request apiTypes.GetRuntimeEvmTokensAddressNftsIdRequestObject) (apiTypes.GetRuntimeEvmTokensAddressNftsIdResponseObject, error) {
	ocAddr, err := apiTypes.UnmarshalToOcAddress(&request.Address)
	if err != nil {
		return nil, err
	}
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	nfts, err := srv.dbClient.RuntimeEVMNFTs(ctx, runtime, common.Ptr(uint64(1)), common.Ptr(uint64(0)), ocAddr, &request.Id, nil)
	if err != nil {
		return nil, err
	}
	if len(nfts.EvmNfts) != 1 {
		return apiTypes.GetRuntimeEvmTokensAddressNftsId404JSONResponse{}, nil
	}
	return apiTypes.GetRuntimeEvmTokensAddressNftsId200JSONResponse(nfts.EvmNfts[0]), nil
}

func (srv *StrictServerImpl) GetRuntimeTransactions(ctx context.Context, request apiTypes.GetRuntimeTransactionsRequestObject) (apiTypes.GetRuntimeTransactionsResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	transactions, err := srv.dbClient.RuntimeTransactions(ctx, runtime, request.Params, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeTransactions200JSONResponse(*transactions), nil
}

func (srv *StrictServerImpl) GetRuntimeTransactionsTxHash(ctx context.Context, request apiTypes.GetRuntimeTransactionsTxHashRequestObject) (apiTypes.GetRuntimeTransactionsTxHashResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	transactions, err := srv.dbClient.RuntimeTransactions(ctx, runtime, apiTypes.GetRuntimeTransactionsParams{}, &request.TxHash)
	if err != nil {
		return nil, err
	}
	if len(transactions.Transactions) == 0 {
		return apiTypes.GetRuntimeTransactionsTxHash404JSONResponse{}, nil
	}
	return apiTypes.GetRuntimeTransactionsTxHash200JSONResponse(*transactions), nil
}

func (srv *StrictServerImpl) GetRuntimeEvents(ctx context.Context, request apiTypes.GetRuntimeEventsRequestObject) (apiTypes.GetRuntimeEventsResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	events, err := srv.dbClient.RuntimeEvents(ctx, runtime, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeEvents200JSONResponse(*events), nil
}

func (srv *StrictServerImpl) GetRuntimeAccountsAddress(ctx context.Context, request apiTypes.GetRuntimeAccountsAddressRequestObject) (apiTypes.GetRuntimeAccountsAddressResponseObject, error) {
	ocAddr, err := apiTypes.UnmarshalToOcAddress(&request.Address)
	if err != nil {
		return nil, err
	}
	// request.Address is a required field and so ocAddr should never be nil
	// Nevertheless, we check again for clarity.
	if ocAddr == nil {
		return nil, fmt.Errorf("missing required param: address")
	}
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	account, err := srv.dbClient.RuntimeAccount(ctx, runtime, *ocAddr)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeAccountsAddress200JSONResponse(*account), nil
}

func (srv *StrictServerImpl) GetRuntimeAccountsAddressDelegations(ctx context.Context, request apiTypes.GetRuntimeAccountsAddressDelegationsRequestObject) (apiTypes.GetRuntimeAccountsAddressDelegationsResponseObject, error) {
	ocAddr, err := apiTypes.UnmarshalToOcAddress(&request.Address)
	if err != nil {
		return nil, err
	}
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	delegations, err := srv.dbClient.RuntimeDelegations(ctx, runtime, *ocAddr, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeAccountsAddressDelegations200JSONResponse(*delegations), nil
}

func (srv *StrictServerImpl) GetRuntimeAccountsAddressDebondingDelegations(ctx context.Context, request apiTypes.GetRuntimeAccountsAddressDebondingDelegationsRequestObject) (apiTypes.GetRuntimeAccountsAddressDebondingDelegationsResponseObject, error) {
	ocAddr, err := apiTypes.UnmarshalToOcAddress(&request.Address)
	if err != nil {
		return nil, err
	}
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	delegations, err := srv.dbClient.RuntimeDebondingDelegations(ctx, runtime, *ocAddr, request.Params)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeAccountsAddressDebondingDelegations200JSONResponse(*delegations), nil
}

func (srv *StrictServerImpl) GetRuntimeAccountsAddressNfts(ctx context.Context, request apiTypes.GetRuntimeAccountsAddressNftsRequestObject) (apiTypes.GetRuntimeAccountsAddressNftsResponseObject, error) {
	ocAddrOwner, err := apiTypes.UnmarshalToOcAddress(&request.Address)
	if err != nil {
		return nil, err
	}
	ocAddrToken, err := apiTypes.UnmarshalToOcAddress(request.Params.TokenAddress)
	if err != nil {
		return nil, err
	}
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	nfts, err := srv.dbClient.RuntimeEVMNFTs(ctx, runtime, request.Params.Limit, request.Params.Offset, ocAddrToken, nil, ocAddrOwner)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeAccountsAddressNfts200JSONResponse(*nfts), nil
}

func (srv *StrictServerImpl) GetRuntimeStatus(ctx context.Context, request apiTypes.GetRuntimeStatusRequestObject) (apiTypes.GetRuntimeStatusResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	status, err := srv.dbClient.RuntimeStatus(ctx, runtime)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeStatus200JSONResponse(*status), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflApps(ctx context.Context, request apiTypes.GetRuntimeRoflAppsRequestObject) (apiTypes.GetRuntimeRoflAppsResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	apps, err := srv.dbClient.RuntimeRoflApps(ctx, runtime, request.Params, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeRoflApps200JSONResponse(*apps), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflAppsId(ctx context.Context, request apiTypes.GetRuntimeRoflAppsIdRequestObject) (apiTypes.GetRuntimeRoflAppsIdResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	apps, err := srv.dbClient.RuntimeRoflApps(ctx, runtime, apiTypes.GetRuntimeRoflAppsParams{Limit: common.Ptr(uint64(1)), Offset: common.Ptr(uint64(0))}, &request.Id)
	if err != nil {
		return nil, err
	}
	if len(apps.RoflApps) != 1 {
		return apiTypes.GetRuntimeRoflAppsId404JSONResponse{}, nil
	}
	return apiTypes.GetRuntimeRoflAppsId200JSONResponse(apps.RoflApps[0]), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflAppsIdTransactions(ctx context.Context, request apiTypes.GetRuntimeRoflAppsIdTransactionsRequestObject) (apiTypes.GetRuntimeRoflAppsIdTransactionsResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	transactions, err := srv.dbClient.RuntimeRoflAppTransactions(ctx, runtime, request.Params, request.Id)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeRoflAppsIdTransactions200JSONResponse(*transactions), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflAppsIdInstanceTransactions(ctx context.Context, request apiTypes.GetRuntimeRoflAppsIdInstanceTransactionsRequestObject) (apiTypes.GetRuntimeRoflAppsIdInstanceTransactionsResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	transactions, err := srv.dbClient.RuntimeRoflAppInstanceTransactions(ctx, runtime, request.Params.Method, request.Params.Limit, request.Params.Offset, request.Id, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeRoflAppsIdInstanceTransactions200JSONResponse(*transactions), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflAppsIdInstances(ctx context.Context, request apiTypes.GetRuntimeRoflAppsIdInstancesRequestObject) (apiTypes.GetRuntimeRoflAppsIdInstancesResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	instances, err := srv.dbClient.RuntimeRoflAppInstances(ctx, runtime, request.Params, request.Id, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeRoflAppsIdInstances200JSONResponse(*instances), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflAppsIdInstancesRak(ctx context.Context, request apiTypes.GetRuntimeRoflAppsIdInstancesRakRequestObject) (apiTypes.GetRuntimeRoflAppsIdInstancesRakResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	instances, err := srv.dbClient.RuntimeRoflAppInstances(ctx, runtime, apiTypes.GetRuntimeRoflAppsIdInstancesParams{Limit: common.Ptr(uint64(1)), Offset: common.Ptr(uint64(0))}, request.Id, &request.Rak)
	if err != nil {
		return nil, err
	}
	if len(instances.Instances) != 1 {
		return apiTypes.GetRuntimeRoflAppsIdInstancesRak404JSONResponse{}, nil
	}
	return apiTypes.GetRuntimeRoflAppsIdInstancesRak200JSONResponse(instances.Instances[0]), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflAppsIdInstancesRakTransactions(ctx context.Context, request apiTypes.GetRuntimeRoflAppsIdInstancesRakTransactionsRequestObject) (apiTypes.GetRuntimeRoflAppsIdInstancesRakTransactionsResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	transactions, err := srv.dbClient.RuntimeRoflAppInstanceTransactions(ctx, runtime, request.Params.Method, request.Params.Limit, request.Params.Offset, request.Id, &request.Rak)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeRoflAppsIdInstancesRakTransactions200JSONResponse(*transactions), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflmarketProviders(ctx context.Context, request apiTypes.GetRuntimeRoflmarketProvidersRequestObject) (apiTypes.GetRuntimeRoflmarketProvidersResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	providers, err := srv.dbClient.RuntimeRoflmarketProviders(ctx, runtime, request.Params, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeRoflmarketProviders200JSONResponse(*providers), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflmarketProvidersAddress(ctx context.Context, request apiTypes.GetRuntimeRoflmarketProvidersAddressRequestObject) (apiTypes.GetRuntimeRoflmarketProvidersAddressResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	providers, err := srv.dbClient.RuntimeRoflmarketProviders(ctx, runtime, apiTypes.GetRuntimeRoflmarketProvidersParams{Limit: common.Ptr(uint64(1)), Offset: common.Ptr(uint64(0))}, &request.Address)
	if err != nil {
		return nil, err
	}
	if len(providers.Providers) != 1 {
		return apiTypes.GetRuntimeRoflmarketProvidersAddress404JSONResponse{}, nil
	}
	return apiTypes.GetRuntimeRoflmarketProvidersAddress200JSONResponse(providers.Providers[0]), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflmarketProvidersAddressOffers(ctx context.Context, request apiTypes.GetRuntimeRoflmarketProvidersAddressOffersRequestObject) (apiTypes.GetRuntimeRoflmarketProvidersAddressOffersResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	offers, err := srv.dbClient.RuntimeRoflmarketOffers(ctx, runtime, request.Params, &request.Address, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeRoflmarketProvidersAddressOffers200JSONResponse(*offers), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflmarketProvidersAddressOffersId(ctx context.Context, request apiTypes.GetRuntimeRoflmarketProvidersAddressOffersIdRequestObject) (apiTypes.GetRuntimeRoflmarketProvidersAddressOffersIdResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	offerID, err := hex.DecodeString(request.Id)
	if err != nil {
		return nil, err
	}
	offers, err := srv.dbClient.RuntimeRoflmarketOffers(ctx, runtime, apiTypes.GetRuntimeRoflmarketProvidersAddressOffersParams{Limit: common.Ptr(uint64(1)), Offset: common.Ptr(uint64(0))}, &request.Address, offerID)
	if err != nil {
		return nil, err
	}
	if len(offers.Offers) != 1 {
		return apiTypes.GetRuntimeRoflmarketProvidersAddressOffersId404JSONResponse{}, nil
	}
	return apiTypes.GetRuntimeRoflmarketProvidersAddressOffersId200JSONResponse(offers.Offers[0]), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflmarketProvidersAddressInstancesId(ctx context.Context, request apiTypes.GetRuntimeRoflmarketProvidersAddressInstancesIdRequestObject) (apiTypes.GetRuntimeRoflmarketProvidersAddressInstancesIdResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	instanceID, err := hex.DecodeString(request.Id)
	if err != nil {
		return nil, err
	}
	instances, err := srv.dbClient.RuntimeRoflmarketInstances(ctx, runtime, apiTypes.GetRuntimeRoflmarketInstancesParams{Limit: common.Ptr(uint64(1)), Offset: common.Ptr(uint64(0)), Provider: &request.Address}, instanceID)
	if err != nil {
		return nil, err
	}
	if len(instances.Instances) != 1 {
		return apiTypes.GetRuntimeRoflmarketProvidersAddressInstancesId404JSONResponse{}, nil
	}
	return apiTypes.GetRuntimeRoflmarketProvidersAddressInstancesId200JSONResponse(instances.Instances[0]), nil
}

func (srv *StrictServerImpl) GetRuntimeRoflmarketInstances(ctx context.Context, request apiTypes.GetRuntimeRoflmarketInstancesRequestObject) (apiTypes.GetRuntimeRoflmarketInstancesResponseObject, error) {
	runtime, err := request.Runtime.Validate()
	if err != nil {
		return nil, err
	}
	instances, err := srv.dbClient.RuntimeRoflmarketInstances(ctx, runtime, request.Params, nil)
	if err != nil {
		return nil, err
	}
	return apiTypes.GetRuntimeRoflmarketInstances200JSONResponse(*instances), nil
}
