-- DO NOT MODIFY
-- This file was autogenerated by the oasis-indexer migration generator.
BEGIN;

-- Registry Backend Data
TRUNCATE test.entities CASCADE;
INSERT INTO test.entities (id)
VALUES
	('gb8SHLeDc69Elk7OTfqhtVgE2sqxrBCDQI84xKR+Bjg='),
	('LaKJUKndAqH57DVExspTjdRTRNGJOSqArzM0pm8REZw='),
	('DcplOZzEDthLHtPyjbtn9nldfzZ5b9r8EJFnD3JTGMI=');

TRUNCATE test.nodes CASCADE;
INSERT INTO test.nodes (id, entity_id, expiration, tls_pubkey, tls_next_pubkey, p2p_pubkey, consensus_pubkey, roles)
VALUES
	('5RIMVgnsN1D/HdvNxXCpE+lWH5U/SGYUrYsvhsTMbyA=', 'gb8SHLeDc69Elk7OTfqhtVgE2sqxrBCDQI84xKR+Bjg=', 13403, 'ULLgoIQNFizH5l6O3YpK6+pD6JYiJ/0bEj0OsXP4x7k=', 'drjBggoGlujuzfoCV/aqhIKrwCaQdclE+Pc/XLx7a2I=', 'ZjerSSlcR3yrd4dff3ZjoPI6TvMivoiwyvNWSXsYzWA=', 's7peyC7dJcqo58KIMJXNQTwIivRPX7OQX0h/eOUs/cU=', 'validator'),
	('jZ2/EOnpmPCxCfd5wrrLINNdZSPWyhIx9UqJgZ8sHYk=', 'LaKJUKndAqH57DVExspTjdRTRNGJOSqArzM0pm8REZw=', 13403, 'SKRouKTSMvdBkXqeJ9ookakoCLBWx44zYFJIN0Tz7ks=', 'ZtZ+GxltIQs6X3aQSituiex8GFduRHAsZFn5kUID7Vg=', 'bpiX0+kFMBa67VBoACbNu4iGuLWm2NBnDTP31Ia7COw=', 'T2rV0W8cTa3tMuWtO7hEtSuUaxtIVSAfZuiB6hlltt8=', 'validator');

TRUNCATE test.runtimes CASCADE;
INSERT INTO test.runtimes (id, suspended, kind, tee_hardware, key_manager)
VALUES
		('000000000000000000000000000000000000000000000000e2eaa99fc008f87f', false, 'compute', 'invalid', 'none');

-- Staking Backend Data
TRUNCATE test.accounts CASCADE;
INSERT INTO test.accounts (address, general_balance, nonce, escrow_balance_active, escrow_total_shares_active, escrow_balance_debonding, escrow_total_shares_debonding)
VALUES
	('oasis1qp000hx7p3elxrglmg6r98zkenk0sjt4ks986dc3', 100, 3, 600, 600, 400, 400),
	('oasis1qp008f6fg9kqk6gt9vxf5yk2d5wv7vm2x5tkc88y', 200, 4, 0, 0, 0, 0),
	('oasis1qp000kj5dj5tf48x0rhzf8298dw78w2yzvza727z', 300, 1, 0, 0, 0, 0),
	('oasis1qp002d6rv8r0zmhfe69th39rm0uaz4j6rsm5glcy', 400, 5, 0, 0, 0, 0);

TRUNCATE test.allowances CASCADE;
INSERT INTO test.allowances (owner, beneficiary, allowance)
VALUES
	('oasis1qp000hx7p3elxrglmg6r98zkenk0sjt4ks986dc3', 'oasis1qp008f6fg9kqk6gt9vxf5yk2d5wv7vm2x5tkc88y', 50);

TRUNCATE test.delegations CASCADE;
INSERT INTO test.delegations (delegatee, delegator, shares)
VALUES
	('oasis1qp000hx7p3elxrglmg6r98zkenk0sjt4ks986dc3', 'oasis1qp000hx7p3elxrglmg6r98zkenk0sjt4ks986dc3', 100),
	('oasis1qp000hx7p3elxrglmg6r98zkenk0sjt4ks986dc3', 'oasis1qp008f6fg9kqk6gt9vxf5yk2d5wv7vm2x5tkc88y', 200),
	('oasis1qp000hx7p3elxrglmg6r98zkenk0sjt4ks986dc3', 'oasis1qp000kj5dj5tf48x0rhzf8298dw78w2yzvza727z', 300);

TRUNCATE test.debonding_delegations CASCADE;
INSERT INTO test.debonding_delegations (delegatee, delegator, shares, debond_end)
VALUES
	('oasis1qp000hx7p3elxrglmg6r98zkenk0sjt4ks986dc3', 'oasis1qp002d6rv8r0zmhfe69th39rm0uaz4j6rsm5glcy', 400, 13567);

-- Governance Backend Data
TRUNCATE test.proposals CASCADE;
INSERT INTO test.proposals (id, submitter, state, deposit, handler, cp_target_version, rhp_target_version, rcp_target_version, upgrade_epoch, cancels, created_at, closes_at, invalid_votes)
VALUES
	(1, 'oasis1qp000kj5dj5tf48x0rhzf8298dw78w2yzvza727z', 'passed', 10, 'test-handler', '4.0.0', '3.0.0', '2.0.0', 8049, 0, 7708, 7876, 0);

TRUNCATE test.votes CASCADE;
INSERT INTO test.votes (proposal, voter, vote)
VALUES
	(1, 'oasis1qp000hx7p3elxrglmg6r98zkenk0sjt4ks986dc3', 'yes'),
	(1, 'oasis1qp008f6fg9kqk6gt9vxf5yk2d5wv7vm2x5tkc88y', 'yes');

COMMIT;
