
name: docker-indexer

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # We need history to determine oasis-indexer version from git tag.
          fetch-depth: '0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Compute version
        # Version oasis-indexer image by date and git revision.
        run: |
          echo "VERSION=$(date +%Y-%m-%d-git$(git rev-parse --short HEAD))" >> $GITHUB_ENV
      - name: Build and push Docker
        uses: docker/build-push-action@v3
        with:
          build-args: |
            VERSION=${{ env.VERSION }}
          context: .
          file: docker/indexer/Dockerfile
          tags: |
            oasislabs/oasis-indexer:latest
            oasislabs/oasis-indexer:latest-${{ env.VERSION }}
          push: true
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
